### ISSUE TITLE
Add NPTEL2020-Indian-English-Speech-Dataset

### ISSUE THREAD

**Issue by Prem-kumar27** [robmsmt/ASR_Audio_Data_Links#5]
Please add this dataset to the list:
https://github.com/AI4Bharat/NPTEL2020-Indian-English-Speech-Dataset

**Comment by robmsmt** [comment]
Thanks for this, it will be a useful addition. I have added it; maybe I should include the download scripts (these failed for me so currently trying torrent)

**Comment by Prem-kumar27** [comment]
Yes, the direct download files are hosted on zenodo, which causes issues on unstable internet connections. Downloading on cloud VMs like GCP, Azure works. 

But downloading via torrent is the easiest and best way since the it's highly compressed version.

Thanks for adding
